import { initializeApp, cert, getApps, getApp } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import fs from "fs";
import path from "path";

let db: FirebaseFirestore.Firestore;

try {
  let app;
  if (!getApps().length) {
    // Determine path based on environment execution
    const isCompiled = __filename.endsWith(".cjs") || __filename.includes("dist");
    const certPath = process.env.GOOGLE_APPLICATION_CREDENTIALS 
      ? process.env.GOOGLE_APPLICATION_CREDENTIALS
      : path.join(process.cwd(), "firebase-applet-config.json");
    
    // We try to use GOOGLE_APPLICATION_CREDENTIALS if it exists (for standard setup).
    // In our AI Studio env, there is no service account JSON generated by default for Firebase Admin.
    // Wait, the set_up_firebase creates a project and firebase-applet-config.json which only has Client config (apiKey, appId, projectID).
    // Let me check if firebase-applet-config.json can be used with Admin SDK `app` init directly if run in GCP environment or we just initialize without cert() because the environment is ADC attached!
    
    app = initializeApp({
       projectId: process.env.FIREBASE_PROJECT_ID || 'gen-lang-client-0981806946',
    });
  } else {
    app = getApp();
  }
  db = getFirestore(app);
} catch (error) {
  console.log("Firebase Admin initialize error:", error);
}

export { db };
